[tox]
skipsdist = True

[testenv]
skip_install = true
allowlist_externals = coverage
commands =
    coverage erase
    coverage run --source='lambdas' -m pytest --junitxml='./tests/reports/unit/junitresults.xml'
    coverage html -d tests/reports/coverage/html --precision=2
    coverage xml -i -o tests/reports/coverage/coverage.xml
    coverage report -m --fail-under=80
setenv =
    PYTHONUTF8=1
    PYTHONIOENCODING=utf-8